name: Split

on:
    push:
        branches:
            - main

jobs:
    build-matrix:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none
                    tools: composer:v2
            -   run: composer install --no-progress --ansi
            -   id: set-packages
                run: echo "::set-output name=packages::$(vendor/bin/monorepo-builder packages-json --names | cut -d ":" -f 2 | sed 's/.$//')"
        outputs:
            packages: ${{ steps.set-packages.outputs.packages }}

    split:
        needs: build-matrix
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix: 
                package: ${{ fromJson(needs.build-matrix.outputs.packages) }}
        steps:
            -   uses: actions/checkout@v2
                # this is required for "WyriHaximus/github-action-get-previous-tag" workflow
                # see https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
                with:
                    fetch-depth: 0

            # see https://github.com/WyriHaximus/github-action-get-previous-tag
            #-   id: previous_tag
            #    uses: "WyriHaximus/github-action-get-previous-tag@master"

            # Uses an action in the root directory
            -   uses: TomasVotruba/github-action-monorepo-split@f9f1313304dcf9bec66b403abb1ca8400e493a1b
                env:
                    GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
                with:
                    package-directory: 'packages/${{ matrix.package }}'
                    split-repository-organization: 'LongRunning'
                    split-repository-name: '${{ matrix.package }}'
                    user-email: longrunning-bot@users.noreply.github.com
                    user-name: longrunning-bot
                    branch: main
                    #tag: ${{ steps.previous_tag.outputs.tag }}
